### PR TITLE
feat(plugin): Quests completer

### PR DESCRIPTION
**Pull request by happyendermangit**
This plugin completes quests without having the game. **this is useful for quests that rewards you avatar decorations**

The "Complete Quest" button is enabled only if:
- You have uncompleted quests
- You are streaming something
- Someone is watching your stream (your alt or your friend.)

For Web, this requires to install an [extension](https://github.com/SerStars/QuestCompleterExtension/tree/plugin) (only for chrome)

## Screenshots:
image
image
image

### CODE REVIEW

**Comment by mantikafasi** [comment]
fix linter and also dont edit the constants file, as it will create merge conflict in future.
also please move plugin into plusplugins folder

**Comment by happyendermangit** [comment]
Let me do that right now.

**Comment by happyendermangit** [comment]
Done :+1:

**Comment by mantikafasi** [comment]
there is still lots of linter errors.
also dont call webpack functions everytime on functions that's horrible for performance,please declare them on top level with lazy versions like findByPropsLazy

**Comment by mantikafasi** [comment]
also can you please leave the "timezones" plugin alone

**Pull request closed without merging**
